# Generated by Django 2.2.5 on 2019-11-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedday',
            old_name='day',
            new_name='date',
        ),
    ]
